### ISSUE TITLE
Add weekly incidence

### ISSUE THREAD

**Issue by lhelleckes** [michaelosthege/rtlive-dash-de#17]
+ RKI publishes weekly incidence numbers
+ We publish daily numbers)
+ Weekly numbers (x7) should be available for comparison with a disclaimer about the difference in the FAQ

**Comment by MaPePeR** [comment]
I feel like this is not so easy.

I assume one would have to adapt the [`summarize_infections`](https://github.com/rtcovidlive/rtlive-global/blob/22443333d027df9bc974db434958f1f5100a8525/rtlive/export.py#L58-L67) function. But from the looks of it that function is only called with the data for the last day of all sample runs? And I couldn't figure out from where it is actually called. The only reference github finds is in the testcases. To calculate the weekly incidence one would need the last 7 days, as multiplying by 7 would overestimate for rising numbers and underestimate for falling numbers?

Then one would have to add a new scope to `global.js` and `main.js`, but from a first glance it looks like one is mostly a copy of the other?

**Comment by michaelosthege** [comment]
First the easy parts:
Yes `global.js` is mostly a generalized copy of `main.js`.

You couldn't find the calling code, because @lhelleckes and I still didn't get around to publish it. Sorry about that..

Here are the relevant parts:
```python
def export_for_website(country: str, region: str):
    import arviz
    import json
    from matplotlib import pyplot    
    from rtlive import data, plotting, export, model
    from rtlive.sources import data_de
    
    # Load relevant raw/result data
    df = pandas.read_csv(
        'data.csv',
        index_col=["region", "date"],
        parse_dates=["date"]
    ).xs(region)
    df_holidays = pandas.read_excel(
        'testcount_forecast.xlsx', sheet_name='holidays',
        index_col=0, parse_dates=True
    )
    holidays_dict = {
        row.ds : row.name
        for row in df_holidays.itertuples()
    }
    idata = arviz.from_netcdf('trace.nc')

    # summarize for yesterday, because this is most comparable to other methods
    last_date = (date - datetime.timedelta(hours=24)).strftime('%Y-%m-%d')

    # make the detailed plot
    if region == "all":
        title = f'Deutschland, {date_str}'
        rt_comparisons = data_de.get_rki_nowcast(date_str, label_german=True)
        _log.info(f"Plotting {country}/{region} with comparisons: {rt_comparisons.keys()}")
    else:
        title = f'{data_de.DE_REGION_NAMES[region]}, {date_str}'
        rt_comparisons = None
    fig, axs = plotting.plot_details(
        idata,
        vlines={
            date : "",
            **holidays_dict
        },
        prediction_marker=(date, "heute\n"),
        actual_tests=df.new_tests,
        plot_positive="unobserved",
        label_translations=data_de.LABEL_TRANSLATIONS,
        locale_key='de_DE.UTF-8',
        license=LICENSE,
        rt_comparisons=rt_comparisons,
    )
    axs[0].set_title(title)
    fig.savefig(f'{country}_{region}.png')

    # make thumbnail plot
    fig, ax = plotting.plot_thumbnail(idata, locale_key='de_DE.UTF-8', license=LICENSE)
    fig.tight_layout()
    fig.savefig(f'{country}_{region}_thumb.png')

    # export json summary
    new_cases, total_cases, active_cases = model.get_case_curves(idata)
    stacked_r_t = idata.posterior.r_t.stack(sample=('chain', 'draw'))
    population = data.SUPPORTED_COUNTRIES[country.upper()].region_population[region]
    summary = {
        'last_updated': datetime.datetime.utcnow().astimezone(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%S%z').replace('+0000', 'Z'),
        'date': last_date,
        "population": population,
        **export.summarize_r_t(stacked_r_t.sel(date=last_date)),
        **export.summarize_infections(new_cases.sel(date=last_date), population),
        **export.summarize_median_and_hdi(total_cases.sel(date=last_date), "total"),
        **export.summarize_median_and_hdi(active_cases.sel(date=last_date), "active"),
    }
    with open(f'{country}_{region}_summary.json', 'w') as jfile:
        json.dump(summary, jfile)
    return

```

For 7-day incidence one could just add a line into the `summary` dictionary that is called with the corresponding slice from `new_cases`.

@MaPePeR do you have a trace object to test with?

**Comment by MaPePeR** [comment]
Yes, I have a trace file. I hope I find time to take a deeper look into it over the weekend, but can't make any promises, of course.

Thanks for posting the method. That will be incredible helpful.

**Comment by MaPePeR** [comment]
To calculate the weekly incidence only these two lines are needed:

```python
last_date_minus_1w  = (datetime.datetime.strptime(last_date, "%Y-%m-%d") - datetime.timedelta(days=6))
```
For my testing i had to turn `last_date` back into a `datetime` object, but in your code you can probably use the global `date` variable instead?

Add these line to the `summary`:
```python
**export.summarize_median_and_hdi(new_cases.sel(date=slice(last_date_minus_1w, last_date)).sum(axis=0) / population * 100_000, "7d_infections_by_100k")
```

Please check that `new_cases.sel(date=slice(last_date_minus_1w, last_date))` returns 7 days for each sample run in your setup.
I might be off by one there because of a `last_date `and `date` mixup.

**Comment by michaelosthege** [comment]
@MaPePeR Awesome!
I suppose the timedelta is set to 6 days because the bounds are inclusive? (I always have to test stuff like that.)

Ah yes, the `date` is a `datetime.datetime` converted from the `next_execution_date` entry in the context of the Airflow task instance.
I stripped it from the code snippet and apparently overlooked the undefined varaible.

I will add these lines to our Airflow DAG and re-run the export task. After the JSONs wen't live #22 should be good to go.

**Comment by MaPePeR** [comment]
> I suppose the timedelta is set to 6 days because the bounds are inclusive? (I always have to test stuff like that.)

Yes. Also had to trial and error that. But the [documentation for the `sel`](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.sel.html#xarray.DataArray.sel) function confirms, that the bounds are inclusive.
